pipeline:
  changelog:
    image: lawnchairlauncher/drone-changelog:latest
    output: changelog.txt
    when:
      event: push
  restore-cache:
    image: drillster/drone-volume-cache:latest
    restore: true
    mount:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      - "$HOME/.android/build-cache"
    volumes:
      - /tmp/cache:/cache
  build:
    image: runmymind/docker-android-sdk:ubuntu-standalone
    secrets: [ awareness_api_key, store_password, key_password ]
    environment:
      - MAJOR_MINOR=alpha
      - TRAVIS=true
      - TRAVIS_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - TRAVIS_EVENT_TYPE=${DRONE_BUILD_EVENT}
    commands:
      - bash ./gradlew assembleDebug check;
  telegram:
    image: lawnchairlauncher/drone-telegram:latest
    secrets: [ bot_token, channel_id ]
    when:
      event: push
      status: success
  rebuild-cache:
    image: drillster/drone-volume-cache:latest
    rebuild: true
    mount:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      - "$HOME/.android/build-cache"
    volumes:
      - /tmp/cache:/cache

branches:
  include: alpha